import Head from 'next/head'
import { Inter } from 'next/font/google'
import { Paper } from '@/Layout/Paper'
import { Dipslay } from '@/UI/Display/Display'
import Toggler from '@/UI/Toggler/Toggler'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Constructor</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={inter.className}>
        <Paper>
          <Dipslay value={0} />
        </Paper>
      </main>
    </>
  )
}
